kumuluzee:
  name: mag2020-media-manager
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8003
    http:
      port: 8003
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"
  grpc:
    clients:
      - name: awsStorageClient
        port: 9001
        address: localhost
      - name: mediaMetadataClient
        port: 9002
        address: localhost

appproperties:
  rabbitmq:
    chunks-queue-name: MEDIA_CHUNKS_QUEUE
    image-queue-name: IMAGE_QUEUE
    host: localhost
    username: uros
    password: uros123
  services:
    awsstorage:
      url: http://localhost:8002/
      endpoints:
        uploadmedia: v1/awsStorage/media/
        createbucket: v1/awsStorage/bucket/
        getmedia: v1/awsStorage/media/
    mediametadata:
      url: http://localhost:8001/
      endpoints:
        newmediametadata: v1/media/metadata/new/
