kumuluzee:
  name: mag2020-media-metadata
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8003
    http:
      port: 8003
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379