kumuluzee:
  name: mag2020-media-manager
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8003
    http:
      port: 8003
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      supported-methods: "GET, POST, HEAD, OPTIONS, DELETE"
      allow-origin: "*"
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
      rabbit-health-check:
        connection-url: amqp://uros:uros123@localhost:5672/virtualHost?connection_timeout=2000
  opentracing:
    jaeger:
      service-name: mag2020-media-manager
      agent-host: localhost # default agent host
      agent-port: 5775 # default agent port
      reporter:
        log-spans: true
        max-queue-size: 10000
        flush-interval: 1000
      sampler:
        type: const # default sampler type
        param: 1 # default sampler param
        manager-host-port: http://localhost:5775
      traceid-128bit: true
  grpc:
    clients:
      - name: awsStorageClient
        port: 9001
        address: localhost
      - name: mediaMetadataClient
        port: 9002
        address: localhost
mp:
  opentracing:
    server:
      operation-name-provider: http-path
      skip-pattern: /openapi.*|/health.*

appproperties:
  rabbitmq:
    chunks-queue-name: MEDIA_CHUNKS_QUEUE
    image-queue-name: IMAGE_QUEUE
    video-analysis-queue-name: VIDEO_ANALYSIS_QUEUE
    host: localhost
    username: uros
    password: uros123
  services:
    awsstorage:
      url: http://localhost:8002/
      endpoints:
        uploadmedia: v1/awsStorage/media/
        createbucket: v1/awsStorage/bucket/
        getmedia: v1/awsStorage/media/
    mediametadata:
      url: http://localhost:8001/
      endpoints:
        newmediametadata: v1/media/metadata/new/
    mediachunks:
      url: http://localhost:8004/
